name: urlspliter
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/ipconfiger/UrlSpliter
author: alex <superpowerlee@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
